/**
 * Re-exports Frostboard's toast hook so views import feedback helpers from a
 * single, stable path (`@/hooks/useToast`). The implementation lives with the
 * provider in `@/components/layout/toast-provider` — an SSR-safe replacement for
 * chiselui's `ToastProvider`, which renders its portal during prerender and so
 * cannot be statically generated by Next.js.
 */
export {
  useToast,
  type ToastOptions,
  type ToastVariant,
} from "@/components/layout/toast-provider";
